version: 0.2

phases:
  pre_build:
    commands:
      - echo "JAVA_HOME is set to $JAVA_HOME"
  build:
    commands:
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - echo "Using JAVA_HOME $JAVA_HOME"
      - mvn package
      - ls -l target/

artifacts:
  files:
    - "target/*.jar"
  discard-paths: yes
