version: 0.2

phases:
  install:
    commands:
      - yum install -y java-17-amazon-corretto-devel
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - yum install -y maven
  build:
    commands:
      - mvn package
artifacts:
  files:
    - target/my-application.jar